// Generated by CoffeeScript 1.10.0
(function() {
  module.exports = {
    maxData: 1000,
    sensorData: [],
    post: function(req, res) {
      var data, timestamp;
      data = req.body;
      timestamp = Date.now();
      if (this.sensorData.length === 0) {
        this.sensorData.push(data);
      }
      this.sensorData = [req.body].concat(this.sensorData);
      if (this.sensorData.length > this.maxData) {
        this.sensorData.pop();
      }
      console.log(this.sensorData.length);
      return res.ok();
    },
    latestData: function() {
      return sensorData[0];
    }
  };

}).call(this);

//# sourceMappingURL=MeasurementsController.js.map
