// Generated by CoffeeScript 1.10.0
(function() {
  var extend;

  extend = require('util')._extend;

  module.exports = {
    sensorAnalyzers: {
      pulse: function(pulse) {
        return PulseAnalyzer.analyze(pulse);
      },
      eyesOpen: function(eyesOpen) {
        return EyesOpenAnalyzer.analyze(eyesOpen);
      },
      headPose: function(pose) {
        return HeadPoseAnalyzer.analyze(pose);
      },
      muscleActivity: function(muscle) {
        return MuscleAnalyzer.analyze(muscle);
      }
    },
    symptomAnalyzers: {
      heartattack: function(sensorAnalyzers) {
        return HeartAttackAnalyzer.analyze(sensorAnalyzers);
      },
      unconsciousness: function(sensorAnalyzers) {
        return UnconsciousnessAnalyzer.analyze(sensorAnalyzers);
      },
      sleeping: function(sensorAnalyzers) {
        return SleepingAnalyzer.analyze(sensorAnalyzers);
      }
    },
    analyze: function(latestMeasurement) {
      var analyzedSensors, analyzer, property, ref, ref1, result;
      analyzedSensors = {};
      result = {};
      ref = this.sensorAnalyzers;
      for (property in ref) {
        analyzer = ref[property];
        analyzedSensors[property] = analyzer(latestMeasurement[property]);
      }
      console.log(latestMeasurement);
      console.log(analyzedSensors);
      ref1 = this.symptomAnalyzers;
      for (property in ref1) {
        analyzer = ref1[property];
        result = extend(result, analyzer(analyzedSensors));
      }
      console.log(result);
      return result;
    }
  };

}).call(this);

//# sourceMappingURL=AnalysisService.js.map
