// Generated by CoffeeScript 1.10.0
(function() {
  module.exports = {
    analyze: function(eyesOpen) {
      if (eyesOpen < 0.2) {
        return 1;
      } else {
        return 0;
      }
    }
  };

}).call(this);

//# sourceMappingURL=EyesOpenAnalyzer.js.map
