// Generated by CoffeeScript 1.10.0
(function() {
  module.exports = {
    analyze: function(pose) {
      if (pose === void 0) {
        return 1;
      } else if (pose.rotation.x > 50) {
        return 1;
      } else if (pose.rotation.y > 50) {
        return 1;
      } else if (pose.rotation.z > 50) {
        return 1;
      } else {
        return 0;
      }
    }
  };

}).call(this);

//# sourceMappingURL=HeadPoseAnalyzer.js.map
