// Generated by CoffeeScript 1.10.0
(function() {
  module["export"] = {
    analyze: function(muscle) {
      return 0;
    }
  };

}).call(this);

//# sourceMappingURL=MuscleActivityAnalyzer.js.map
