// Generated by CoffeeScript 1.10.0
(function() {
  module.exports = {
    analyze: function(pulse) {
      if (pulse < 40) {
        return 1 - (Math.max(pulse - 20, 0) / 20);
      } else if (pulse >= 180) {
        return Math.min((pulse - 180) / 10, 1);
      } else {
        return 0;
      }
    }
  };

}).call(this);

//# sourceMappingURL=PulseAnalyzer.js.map
