// Generated by CoffeeScript 1.10.0
(function() {
  module.exports = {
    warntimeEyesOpen: null,
    analyze: function(sensorAnalyzers) {
      var critical, date, warning;
      warning = false;
      critical = false;
      date = Date.now();
      if (sensorAnalyzers.eyesOpen === 1) {
        warning = true;
        if (this.warntimeEyesOpen === null) {
          this.warntimeEyesOpen = date;
        }
        if ((date - this.warntimeEyesOpen) >= 5000) {
          critical = true;
        }
      }
      return {
        sleepingWarning: warning,
        sleepingCritical: critical
      };
    }
  };

}).call(this);

//# sourceMappingURL=SleepingAnalyzer.js.map
